name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\(.*\))?:/i'
  - label: 'fix'
    title:
      - '/^fix(\(.*\))?:/i'
  - label: 'chore'
    title:
      - '/^chore(\(.*\))?:/i'
  - label: 'ci'
    title:
      - '/^ci(\(.*\))?:/i'
  - label: 'docs'
    title:
      - '/^docs(\(.*\))?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.*\))?:/i'
  - label: 'style'
    title:
      - '/^style(\(.*\))?:/i'
  - label: 'test'
    title:
      - '/^test(\(.*\))?:/i'
  - label: 'perf'
    title:
      - '/^perf(\(.*\))?:/i'
  - label: 'build'
    title:
      - '/^build(\(.*\))?:/i'
  - label: 'breaking'
    title:
      - '/^.*!:/i'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance & Polish'
    labels:
      - 'chore'
      - 'refactor'
      - 'docs'
      - 'style'
      - 'perf'
      - 'test'
      - 'ci'
      - 'build'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feat'
      - 'feature'
  default: patch

template: |
  ## What's Changed
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
